[package]
name = "x"
version = "0.1.0"
edition.workspace = true
description = "Rootless, cross-platform Nix package runner"
license.workspace = true
rust-version.workspace = true

[dependencies]
libx.workspace = true
clap.workspace = true
color-eyre.workspace = true
eyre.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
